services:
  revisador-casos-clinicos:
    build:
      context: .
      args:
        - GIT_EMAIL=your-email@example.com
        - GIT_NAME=Your Name
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    
  echo-branch:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
      - ./echo-branch.sh:/app/echo-branch.sh
    entrypoint: ["/bin/bash", "-c", "chmod +x /app/echo-branch.sh && /app/echo-branch.sh"]
    depends_on:
      - revisador-casos-clinicos